#+LATEX_CLASS_OPTIONS: [12pt]
#+OPTIONS: num:nil toc:nil
#+LATEX_HEADER: \usepackage[sc, osf]{mathpazo}
#+LATEX_HEADER: \usepackage[euler-digits, small]{eulervm}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{mathrsfs}
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \usepackage[left = 2cm, right = 2cm, top = 2cm, bottom = 2cm]{geometry}
#+LATEX_HEADER: \def\R{\mathbb{R}}
#+LATEX_HEADER: \def\H{\mathbb{H}}
#+LATEX_HEADER: \def\x{\mathbf{x}}
#+LATEX_HEADER: \def\mob{\textup{M{\"o}bius}}
#+LATEX_HEADER: \def\C{\mathbb{C}}
#+LATEX_HEADER: \def\P{\mathbb{P}}
#+LATEX_HEADER: \def\Cinf{C^{\infty}}
#+LATEX_HEADER: \def\A{\mathscr{A}}
#+LATEX_HEADER: \def\B{\mathscr{B}}
#+LATEX_HEADER: \renewcommand{\theenumi}{(\alph{enumi})}
#+LATEX_HEADER: \newcommand\sectionbreak{\clearpage}

* Chapter 1: Manifolds
** 1
   In the first part, verify that the conditions required for metric
   is satisfied.

   In the second part, one has to show that $B_{\bar{d}}(x,
   \varepsilon') \subset B_{d}(x, \epsilon) \subset B_{\bar{d}}(x,
   \varepsilon)$.
   
** 2
   This is trivial. 
** 3
   1. Basically, you have to make use of the local properties of
      Euclidean spaces.

   2. For (b), proceed in the following manner: Take $x_0 \in X$, let
      the set $A$ be all points $y$ in $X$ such that there exists a
      path from $x_0$ to $y$. Show that this set is both open and
      closed; since the space is connected, $A = X$.

   3. Basically, one has to proceed in a similar fashion. But the
      issue is that the line connecting the limit point $x$ and a
      point $y$ in its neighborhood need not form an arc (the issue is
      that this need not result in a one-one path.)

      To resolve this, observe that a continuous image of $[0, 1]$
      will be compact. Since the space is locally metrizable, if $x$
      is a limit point of $A$, there is a sequence of points $\{x_n\}$
      that converges to $x$ in $A$. Choose a point $x_n$ in some
      metrizable neighborhood of $x$, now the infimum of distances
      from $x$ to this compact set will be realized at a point $y$ in
      the range. Join $y$ and $x$ and remove the remainder of the path
      from $y$ to $x_n$ to obtain an arc to $x$, i.e., $x \in A$.

      Similarly, one can prove openness of $A$, and from the fact that
      $A$ is connected, we see that $A = X$.
      
** 4
   1. Topologist's Sine curve. 
      
   2. Trivial.

   3. Define the relation $\sim$ on $X$ by $x \sim y$ if there is an
      connected subset of $X$ that contains $x$ and $y$. The
      equivalence classes of $X$ under $\sim$ are called the connected
      components of $X$.
   
      It is easy to see that connected components are indeed
      connected, (show that $C$ is the union of connected sets
      containing at least a point in common.)

      If all the connected components are open, then the space is
      locally connected, since for every point $x$ in $X$, $C_x$ be
      the connected component to which $x$ belongs. Since $C_x$ is
      open, this is the neighborhood that we are looking.

      Suppose the space is locally connected. Let $C_x$ be a connected
      component, and pick $x\in C_x$. There exists an open connected
      neighborhood $U$. Since $U$ is connected, it has to lie entirely
      in $C_x$, and hence $C_x$ is open.

   4. Trivial

   5. Follows from 4.
** 5
   1. This is trivial.
      
   2. Follows from the fact that for $n \neq m$, $\R^n$ is not
      homeomorphism to $\R^m$.
** 6
   1. It is easy to see that open subsets of an $n$ manifold is an $n$
      manifold.

      Suppose $M'$ be an $n$ sub-manifold of $M$. If $M'$ is not open,
      then for some $x \in M'$, every neighborhood of $x$ contains a
      point outside of $M'$, but there exists a neighborhood of $M'$
      that is homeomorphic to $\R^n$ and hence this neighborhood is
      open in $M$, a contradiction to the fact that $M'$ is not open.

   2. Let $x$ be a point of $M$ which has a neighborhood of dimension
      $n$. Define $A$ to be all points of $M$ that has dimension equal
      to $n$. It is enough to show that $A$ is both open and closed.

      $A$ is open: If $y \in A$, then $y$ has a neighborhood
      homeomorphic to $\R^n$; clearly all points in these neighborhood
      lies in $A$, i.e., $A$ is open.

      $A$ is closed: the space is locally metrizable, let $y$ be a
      limit point of $A$, $\{y_n\}$ be a sequence of points in $A$
      that converges to $y$, if $y$ has a neighborhood of dimension
      $m$ where $m \neq n$, we have a contradiction. Since for large
      enough $n$, $x_n$ has a neighborhood homeomorphic to $\R^n$ and
      also another neighborhood homeomorphic to $\R^m$ (I'm taking for
      faith that this can't happen.)

      On second thought, we don't have to summon the
      locally-metrizable property.
** 7
   1. An easy application of the intermediate value theorem.
      
   2. I'm assuming that by an interval, the author is referring to an
      open interval, i.e., sets of the form $(a, b)$.

      This is trivial from 1.

   3. I'm assuming that by "f is homeomorphism", the author is
      referring to the fact that $f$ is a homeomorphism between $I$
      and $f(I)$.

      This is trivial from 2.
** TODO 8
   1. It is easy to see that two components cannot be bounded at the
      same time, for, if they are bounded (call the components $B$ and
      $C$), then $\R = A \cap B \cap C$ is also bounded, a
      contradiction.

      So it is enough to show that one component is bounded. WLOG,
      assume that $0$ lies "inside" the $A$. Let $0$ belong to the
      component $B$. Since $A$ is compact, $A$ is bounded and thus the
      "inside" of $A$ is bounded.
      
   2. 
      
** TODO 9
   1. Pick a point in $\R$, then $\R - \{x\}$ is disconnected, while
      $\R^n - \{x\}$, where $n > 1$, is connected.
      
   2.
** TODO 11
   The manifold $M$ is $\sigma$ compact, let $M = \cup M_i$, where
   $M_i$ is compact.

   Recall that compact metrizable spaces are first
   countable. Basically one has to take the countable union of all
   these countable sets to get a countable base for $M$.

   Again, compact metrizable spaces are also
** 12
   1. $f(x, y) = \frac{-2x}{y - 1}$.
      
   2. $f(x_1, x_2, \cdots, x_n) = (\frac{-2x_1}{x_n -1},
      \frac{2x_1}{x_n - 1}, \cdots, \frac{-2x_{n-1}}{x_n - 1})$.
** 13
   1. One has to show that the two definitions (the original
      definition, and the definition in which open sets need not
      contain the antipodal point), will give rise to the same
      topology.

      Let us denote the set $\{-p \colon p \in V\}$ by $-V$. Since
      $\phi(p) = -p$ is a homeomorphism from $S^1$ onto $S^1$, $V$ is
      homeomorphic to $-V$. In the second definition, observe that
      $f(V \cap (-V)) = f(V)$.

   2. In case of the $\mob$ strip, the issue is that the new
      definition will produce sets that are not open as per the
      original definition. For example $V = [0, 1/3) \times (-1, 0)$
      is open in $[0, 1] \times (-1, 1)$; the new definition asserts
      that $f(V) = [[0, 1/2) \times (-1, 0)]$ is open in the $\mob$
      strip, but it isn't open as per the original definition.

      The two mappings differ in the symmetry of the map $f$.
** TODO 14
   1. 
      
   2. This follows from the definition of $\P^2$.
** 15
   1. Imagine $S^1$ lying inside $\C$, consider the map $f \colon S^1
      \rightarrow S^1$ defined by $f(z) = z^2$. It is easy to see that
      this map is a quotient map since saturated open sets are mapped
      to open sets of $S^1$. (I think that saturated sets are of the
      form $V = V \cap (-V)$.)

      Then it can be seen that the quotient space under this map is
      $\P^1$. There is a natural map $g \colon \P^1 \rightarrow S^1$
      such that $g(p(x)) = f(x)$ where $p \colon S^1 \rightarrow \P^1$
      is the identification map. Recall that $g$ is a homeomorphism if
      and only if $f$ is a quotient map.
      
   2. Let us imagine things in the following manner. $S^{n}$ is a
      subspace of $\R^{n+1}$ defined by $\Vert \x \Vert = 1$, i.e.,
      all points $\x$ such that $x_1^2 + \cdots + x_{n+1}^2 = 1$.

      One can imagine $S^{n-1}$ as a subspace of $\R^{n}$ in the
      following manner: all points $\x$ such that $x_1^2 + \cdots +
      x_{n}^2 = 1$ and $x_{n+1} = 0$.

      Consider $D^n = \{\x \in \R^n \colon \Vert \x \Vert < 1\}$,
      define $\varphi ((x_1, \cdots, x_n)) = [(x_1, \cdots, x_n,
      x_{n+1})]$ where $[p] = \{p, -p\}$ and $x_{n+1}$ is the positive
      real number that satisfies $x_{n+1}^2 = 1 - (x_1^2 + x_2^2 +
      \cdots + x_{n}^2)$. This map is the required homeomorphism.
** 18 
   1. Consider $\R$, remove a one-point set. $\R - \{x\}$ is not
      connected and since compact sets are bounded, removing a compact
      set from this is not going to make this connected.

      On the other hand, for any compact set $C$ in $\R^n$ will be
      inside the set $[-M, M]^n$ and $\R^n - [-M, M]^n$ is connected

   2. Consider $C = S^{n-1}$ in $\R^n - \{0\}$. This is compact
      relative to $\R^n - \{0\}$ (since it is compact relative to
      $\R^n$.) $R^n - \{0\} - C$ has two connected components, one
      bounded and the other unbounded. In order to make $\R^n - \{0\}
      -K$ connected (where $K$ is a compact set), one has to, at
      least, remove the bounded component completely.

      Imagine the closed set $Y = [a, 0) \cup (0, b]$ for sufficiently
      small $a$ and $b$ such that $Y$ lies entirely in $K$. $Y$ is
      closed, since $Y = [a, b] \cap (\R^n - \{0\})$ and being a
      closed subset of $K$, it is compact. This is a contradiction.
** 19
   1. Given any compact subset $C$ of $\R$, pick a closed interval
      that contains $C$, say $K$, then $\R - K$ has two components. To
      satisfy the property that $\varepsilon (K) \subset \varepsilon
      (C)$, $\varepsilon (C)$ has to be the component of $\R - C$ that
      contains one of the components of $\R - K$. Thus there are two
      ways of doing this, i.e., $\R$ has two ends.

   2. We repeat the same trick. Given any compact subset $C$ of
      $\R^n$, $n > 1$, pick a closed $n$ cell that contains $C$, say
      $K$, then $\R - K$ has exactly one component. We are forced to
      that components of $\R - C$ that contains $\R - K$, i.e., $\R^n$
      has one end.

      Suppose $X$ "has one end", then for repeat the above step to see
      that $X$ is one ended.

      Suppose $X$ is one ended. Suppose for a compact set $C$, $X - C$
      has more than one component and for every compact set $K$ such
      that $C \subset K$, $X - K$ has more than one component, then
      clearly, we have more than one choice for $\varepsilon (C)$, a
      contradiction.

   3. Refer to Theorem 29.1 in Topology, Munkres.

      $\R \cup \varepsilon (R) = [0, 1]$ (Two point compactification
      of $\R$.)

      $\R^n \cup \varepsilon (\R^n) = S^n$ (One point compactification
      of $\R^n$.)
** TODO 25
   1. This is obvious from the fact that $\R^n$ can be "embedded" in
      $\H^n$ (that is, there is a continuous map from $\R^n$ to $\H^n$
      that is homeomorphic to the image.)
      
   2. There are points on manifolds with boundary that do not have
      neighborhoods homeomorphic to $\R^n$. We call the collection of
      all these points as $\partial M$ or the boundary of the points.

      It is easy to show that $\partial M$ is a closed subset of $M$,
      for if $x$ is a limit point of $\partial M$ and if $x$ has a
      neighborhood that is homeomorphic to $\R^n$, then this
      neighborhood also contains a point from $\partial M$, which is a
      contradiction.

      Consider the space $M - \partial M$ with the subspace
      topology. It is easy to see that all points of these space have
      a neighborhood homeomorphic to $\R^n$ ($n$ may vary), and hence
      a manifold without boundary by definition.

      Consider the space $\partial M$. If $p$ is a point on $\partial
      M$ and $V$ be a neighborhood that is homeomorphic to $\H^n$
      ($\H^n$ can be thought of as $\R^{n-1} \times [0, \infty)$.) Let
      $\phi\colon V \rightarrow \H^n$ be such a diffeomorphism, then
      we claim that $p$ is a point of $\partial M$ if and only if for
      $\phi (x) = 0$.

      From the above claim, it is easy to see that $\partial M$, with
      the subspace topology is a manifold.

   3. 
      
* Chapter 2: Differentiable Structures
** 1
   1. Clearly, the symmetric and reflexive properties are satisfied,
      but there are issues with transitivity.

      Consider the following maps:

      $$\begin{array}{c}
      a \colon A \rightarrow \R^n \\
      b \colon B \rightarrow \R^n \\
      c \colon C \rightarrow \R^n \end{array}
      $$

      The $\Cinf$ related only means that the composition of one map
      and the inverse of the other map is $\Cinf$ on the region were
      their domain overlaps. It could be true that $a \circ c^{-1}$
      need not be $\Cinf$ on $A \cap C$. An explicit example should be
      easy to construct.

   2. This has to do with the fact that $\A$ is an Atlas, and the
      newly added maps are all $\Cinf$ related to *all* maps in the
      Atlas $\A$.

      Let $\A'$ be the maximal atlas corresponding to $\A$. We have to
      prove the following: $(x, X)$ and $(y, Y)$ be two coordinates
      then $x$ and $y$ are $\Cinf$ related.

      When $x$ or $y$ belongs to $\A$, this is trivial. It is enough
      to prove for $x$ and $y$ not in $\A$.

      WLOG, assume that there is a chart $(u, U) \in \A$ such that $A
      \in X \cap Y$ (in the general case, we have to repeat the
      following procedure for every charts.)

      Thus $y \circ (x^{-1} = (y \circ u^{-1}) \circ (u \circ x^{-1})$
      and hence is $\Cinf$; similarly $x \circ y^{-1}$ is also $\Cinf$.
   
** TODO 2
** 3
   1. This is trivial from the fact that differentiability implies
      continuity and chain rule. (I'm assuming that these $\Cinf$
      functions are from $\R^n$ to $\R^m$.)
      
   2. The only if part can be easily seen from the fact that

      $$g \circ f \circ x^{-1} = (g \circ y^{-1} ) \circ (y \circ f
      \circ x^{-1}).$$

      where $(x, A), (y, B)$ are charts of $M$ and $N$ respectively.

      To show the only if part, choose $g = y^{i}$ and $g \circ f =
      f^{i}$ is $\Cinf$ map from $M$ into $\R$ for all $i = 1, 2,
      \cdots, m$ (here $m$ is the dimension of $N$.) Which is
      equivalent to saying that the map $f$ is $\Cinf$. (See result
      (4) in page 31.)
** 4
   There are infinite number of non-distinct ones. For example the
   ones that are generated by monomials of odd degree will be
   distinct. (I'm not sure if there is a better answer to this.)
** TODO 5
   1. To say that an Atlas $\A$ is a maximal means the following: if
      $h$ is a homeomorphism and such that it is $\Cinf$ related to
      all elements of $\A$, then $h \in \A$.

      Assume that $\A$ is maximal. Define $\A'$ to be the collection
      of all $(x, U)$ in $\A$ with $U \subset N$. Suppose that $h$ is
      a homeomorphism of an open subset of $N$ into $\R^m$ that is
      $\Cinf$ related to all elements of $N$, then clearly it can be
      thought of as a homeomorphism of an open subset of $M$ into
      $\R^m$ and this map is $\Cinf$ related to all elements of $\A$,
      i.e., $h \in \A$ which implies that $h \in \A'$.
      
   2. A subset $U$ of $N$ is open in $N$ if and only if there exists
      an open set in $M$ such that $U = N \cap M$. Clearly, the set of
      all $(x\vert_{V \cap N}, V \cap N)$ contains $\A'$; this
      collection is an Atlas. The equivalence follows from the fact
      that $\A'$ is maximal.

   3. To prove that $i\colon N \rightarrow M$ is $\Cinf$, we need to
      show the following:

      For $(y, Y) \in \A'$ and $(x, X) \in \A$, the map $x \circ i
      \circ y^{-1}$ is $\Cinf$ (for all such choices of $x$ and $y$.)

      Since $(y, Y) = (z\vert_{V \cap N}, V \cap N)$ for some $(z, V)
      \in \A$, and $x \circ i = x \vert_{N \cap A}$, we see that $x
      \circ i \circ y^{-1} = x \vert_{N \cap A} \circ z^{-1} \vert_{N
      \cap V}$ and the RHS is, by definition of $\A$, $\Cinf$.
** 6
   Can be verified easily. (Refer to problem 1.12 for explicit form of
   $P_1$)
** 7
   1. This was motivated by example (2), page 33. In $\R^n$, one can
      construct a $\Cinf$ function that joins any two points and such
      that the derivative at both the end points equal to the zero
      vector (2 provides a geometric picture of this.) With this in
      mind, we can proceed.

      Consider points $p$ and $q$ on a $\Cinf$ manifold $(M,
      \A)$. Consider the arc from $p$ to $q$ (refer problem 1.3 (c)
      for existence of such an arc.) Now consider all charts $(x, U)$
      such that the intersection of the arc and the set $U$ is
      non-empty. By compactness of the arc, one can choose finitely
      many such charts that covers the arc. In the range of these
      charts form the $\Cinf$ function, paste them.

   2. One can adapt the above construction to form a one-one map that
      is $\Cinf$.
** TODO 8 
** 9 
   Let $S^n$ be covered using the standard atlas containing $2n$
   homeomorphism, say $\A$; define $\A'$ to be the maximal atlas of
   the aforementioned atlas.

   Observe that every chart in $(x, U) \in \A$ satisfies are such that
   the the map $g\colon S^n \rightarrow P^n$ has an inverse when
   restricted on $U$. Thus define $\B$ by taking the collection of all
   sets $x \circ g^{-1}$; clearly this is an atlas of $\P$. Let us
   call the maximal atlas of $\B$ as $\B'$. This is how we define
   $\Cinf$ structure on $\P$. (I'm assuming that this is the
   differentiable structure that Spivak is talking about.)

   One can show that if $x$ is an element of $\A'$ if and only if
   there is an element $z$ in $\B'$ such that $x = z \circ g$. The
   theorem easily follows from this remark.

   The rank of $f$ and $f \circ g$ are same.
** 10 
   1. Obvious. At every point $p$, the function is $\Cinf$, i.e., $f$
      is $\Cinf$.
      
   2.
** 11
   One can write down $D_j g$ as the limit of $(g(x + h_j (0, 0
   \cdots, 0, 1)) - f(x)) / h_j$ as $h_j \rightarrow 0$. This limit
   exists, hence the left and right limits exists and agrees with each
   other. It is easy to see that, in both cases ($g$ replaced by $h$)
   the right limit is the same (as $g$ agrees with $f$) and hence $D_j
   g = D_j h$.
** TODO 12
   The natural way to define a $\Cinf$ structure on $\partial M$ is
   the following: let $(M, \A)$ be a $\Cinf$ structure on $M$, then
   define $\B$ by taking the collection of all charts
   $(x\vert_{\partial M}, U \cap\partial M)$, where $(x, U)$ is a
   chart of $M$.

   Clearly, $\B$ is an atlas. It can be easily shown that this is also
   a maximal atlas. It can be shown that under this structure the
   inclusion map is $\Cinf$, homeomorphic to its image, and hence an
   imbedding.

   We need to prove the uniqueness of this structure .
** 16
   Note that the function $p (x) / exp (-x)$ where $p$ is a polynomial
   has a limit $0$ as $x \rightarrow \infty$. 
** 19
   Follows from the hint. 

