#+LATEX_CLASS_OPTIONS: [12pt]
#+OPTIONS: num:nil toc:nil
#+LATEX_HEADER: \usepackage[sc, osf]{mathpazo}
#+LATEX_HEADER: \usepackage[euler-digits, small]{eulervm}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage[left = 2cm, right = 2cm, top = 2cm, bottom = 2cm]{geometry}
#+LATEX_HEADER: \def\R{\mathbb{R}}
#+LATEX_HEADER: \def\x{\mathbf{x}}
#+LATEX_HEADER: \def\mob{\textup{M{\"o}bius}}
#+LATEX_HEADER: \def\C{\mathbb{C}}
#+LATEX_HEADER: \def\P{\mathbb{P}}
* Chapter 1: Manifolds
** 1
   In the first part, verify that the conditions required for metric
   is satisfied.

   In the second part, one has to show that $B_{\bar{d}}(x,
   \varepsilon') \subset B_{d}(x, \epsilon) \subset B_{\bar{d}}(x,
   \varepsilon)$.
   
** 2
   This is trivial. 
** 3
   Basically, you have to make use of the local properties of the
   Euclidean space.

   For (b), proceed in the following manner: Take $x_0 \in X$, let the
   set $A$ be all points $y$ in $X$ such that there exists a path from
   $x_0$ to $y$. Show that this set is both open and closed; since the
   space is connected, $A = X$.

   For (c), I'm guessing that we have to follow in a similar
   fashion. But here, to show that $A$ is both open and closed looks
   difficult.
** 4
   1. Topologist's Sine curve. 
      
   2. Trivial.

   3. Define the relation $\sim$ on $X$ by $x \sim y$ if there is an
      connected subset of $X$ that contains $x$ and $y$. The
      equivalence classes of $X$ under $\sim$ are called the connected
      components of $X$.
   
      It is easy to see that connected components are indeed
      connected, (show that $C$ is the union of connected sets
      containing at least a point in common.)

      If all the connected components are open, then the space is
      locally connected, since for every point $x$ in $X$, $C_x$ be
      the connected component to which $x$ belongs. Since $C_x$ is
      open, this is the neighborhood that we are looking.

      Suppose the space is locally connected. Let $C_x$ be a connected
      component, and pick $x\in C_x$. There exists an open connected
      neighborhood $U$. Since $U$ is connected, it has to lie entirely
      in $C_x$, and hence $C_x$ is open.

   4. Trivial

   5. Follows from 4.
** 5
   1. This is trivial.
      
   2. Follows from the fact that for $n \neq m$, $\R^n$ is not
      homeomorphism to $\R^m$.
** 6
   1. It is easy to see that open subsets of an $n$ manifold is an $n$
      manifold.

      Suppose $M'$ be an $n$ sub-manifold of $M$. If $M'$ is not open,
      then for some $x \in M'$, every neighborhood of $x$ contains a
      point outside of $M'$, but there exists a neighborhood of $M'$
      that is homeomorphic to $\R^n$ and hence this neighborhood is
      open in $M$, a contradiction to the fact that $M'$ is not open.

   2. Let $x$ be a point of $M$ which has a neighborhood of dimension
      $n$. Define $A$ to be all points of $M$ that has dimension equal
      to $n$. It is enough to show that $A$ is both open and closed.

      $A$ is open: If $y \in A$, then $y$ has a neighborhood
      homeomorphic to $\R^n$; clearly all points in these neighborhood
      lies in $A$, i.e., $A$ is open.

      $A$ is closed: the space is locally metrizable, let $y$ be a
      limit point of $A$, $\{y_n\}$ be a sequence of points in $A$
      that converges to $y$, if $y$ has a neighborhood of dimension
      $m$ where $m \neq n$, we have a contradiction. Since for large
      enough $n$, $x_n$ has a neighborhood homeomorphic to $\R^n$ and
      also another neighborhood homeomorphic to $\R^m$ (I'm taking for
      faith that this can't happen.)

      On second thought, we don't have to summon the
      locally-metrizable property.
** 7
   1. An easy application of the intermediate value theorem.
      
   2. I'm assuming that by an interval, the author is referring to an
      open interval, i.e., sets of the form $(a, b)$.

      This is trivial from 1.

   3. I'm assuming that by "f is homeomorphism", the author is
      referring to the fact that $f$ is a homeomorphism between $I$
      and $f(I)$.

      This is trivial from 2.
** TODO 8
   1. It is easy to see that two components cannot be bounded at the
      same time, for, if they are bounded (call the components $B$ and
      $C$), then $\R = A \cap B \cap C$ is also bounded, a
      contradiction.

      So it is enough to show that one component is bounded. WLOG,
      assume that $0$ lies "inside" the $A$. Let $0$ belong to the
      component $B$. Since $A$ is compact, $A$ is bounded and thus the
      "inside" of $A$ is bounded.
      
   2. 
      
** TODO 9
   1. Pick a point in $\R$, then $\R - \{x\}$ is disconnected, while
      $\R^n - \{x\}$, where $n > 1$, is connected.
      
   2.
** TODO 11
   The manifold $M$ is $\sigma$ compact, let $M = \cup M_i$, where
   $M_i$ is compact.

   Recall that compact metrizable spaces are first
   countable. Basically one has to take the countable union of all
   these countable sets to get a countable base for $M$.

   Again, compact metrizable spaces are also
** 12
   1. $f(x, y) = \frac{-2x}{y - 1}$.
      
   2. $f(x_1, x_2, \cdots, x_n) = (\frac{-2x_1}{x_n -1},
      \frac{2x_1}{x_n - 1}, \cdots, \frac{-2x_{n-1}}{x_n - 1})$.
** 13
   1. One has to show that the two definitions (the original
      definition, and the definition in which open sets need not
      contain the antipodal point), will give rise to the same
      topology.

      Let us denote the set $\{-p \colon p \in V\}$ by $-V$. Since
      $\phi(p) = -p$ is a homeomorphism from $S^1$ onto $S^1$, $V$ is
      homeomorphic to $-V$. In the second definition, observe that
      $f(V \cap (-V)) = f(V)$.

   2. In case of the $\mob$ strip, the issue is that the new
      definition will produce sets that are not open as per the
      original definition. For example $V = [0, 1/3) \times (-1, 0)$
      is open in $[0, 1] \times (-1, 1)$; the new definition asserts
      that $f(V) = [[0, 1/2) \times (-1, 0)]$ is open in the $\mob$
      strip, but it isn't open as per the original definition.

      The two mappings differ in the symmetry of the map $f$.
** TODO 14
   1. 
      
   2. This follows from the definition of $\P^2$.
** 15
   1. Imagine $S^1$ lying inside $\C$, consider the map $f \colon S^1
      \rightarrow S^1$ defined by $f(z) = z^2$. It is easy to see that
      this map is a quotient map since saturated open sets are mapped
      to open sets of $S^1$. (I think that saturated sets are of the
      form $V = V \cap (-V)$.)

      Then it can be seen that the quotient space under this map is
      $\P^1$. There is a natural map $g \colon \P^1 \rightarrow S^1$
      such that $g(p(x)) = f(x)$ where $p \colon S^1 \rightarrow \P^1$
      is the identification map. Recall that $g$ is a homeomorphism if
      and only if $f$ is a quotient map.
      
   2. Let us imagine things in the following manner. $S^{n}$ is a
      subspace of $\R^{n+1}$ defined by $\Vert \x \Vert = 1$, i.e.,
      all points $\x$ such that $x_1^2 + \cdots + x_{n+1}^2 = 1$.

      One can imagine $S^{n-1}$ as a subspace of $\R^{n}$ in the
      following manner: all points $\x$ such that $x_1^2 + \cdots +
      x_{n}^2 = 1$ and $x_{n+1} = 0$.

      Consider $D^n = \{\x \in \R^n \colon \Vert \x \Vert < 1\}$,
      define $\varphi ((x_1, \cdots, x_n)) = [(x_1, \cdots, x_n,
      x_{n+1})]$ where $[p] = \{p, -p\}$ and $x_{n+1}$ is the positive
      real number that satisfies $x_{n+1}^2 = 1 - (x_1^2 + x_2^2 +
      \cdots + x_{n}^2)$. This map is the required homeomorphism.
** 18 
   1. Consider $\R$, remove a one-point set. $\R - \{x\}$ is not
      connected and since compact sets are bounded, removing a compact
      set from this is not going to make this connected.

      On the other hand, for any compact set $C$ in $\R^n$ will be
      inside the set $[-M, M]^n$ and $\R^n - [-M, M]^n$ is connected

   2. Consider $C = S^{n-1}$ in $\R^n - \{0\}$. This is compact
      relative to $\R^n - \{0\}$ (since it is compact relative to
      $\R^n$.) $R^n - \{0\} - C$ has two connected components, one
      bounded and the other unbounded. In order to make $\R^n - \{0\}
      -K$ connected (where $K$ is a compact set), one has to, at
      least, remove the bounded component completely.

      Imagine the closed set $Y = [a, 0) \cup (0, b]$ for sufficiently
      small $a$ and $b$ such that $Y$ lies entirely in $K$. $Y$ is
      closed, since $Y = [a, b] \cap (\R^n - \{0\})$ and being a
      closed subset of $K$, it is compact. This is a contradiction.
** 19
   1. Given any compact subset $C$ of $\R$, pick a closed interval
      that contains $C$, say $K$, then $\R - K$ has two components. To
      satisfy the property that $\varepsilon (K) \subset \varepsilon
      (C)$, $\varepsilon (C)$ has to be the component of $\R - C$ that
      contains one of the components of $\R - K$. Thus there are two
      ways of doing this, i.e., $\R$ has two ends.

   2. We repeat the same trick. Given any compact subset $C$ of
      $\R^n$, $n > 1$, pick a closed $n$ cell that contains $C$, say
      $K$, then $\R - K$ has exactly one component. We are forced to
      that components of $\R - C$ that contains $\R - K$, i.e., $\R^n$
      has one end.

      Suppose $X$ "has one end", then for repeat the above step to see
      that $X$ is one ended.

      Suppose $X$ is one ended. Suppose for a compact set $C$, $X - C$
      has more than one component and for every compact set $K$ such
      that $C \subset K$, $X - K$ has more than one component, then
      clearly, we have more than one choice for $\varepsilon (C)$, a
      contradiction.

   3. Refer to Theorem 29.1 in Topology, Munkres.

      $\R \cap \varepsilon (R) = [0, 1]$ (Two point compactification
      of $\R$.)

      $\R^n \cap \varepsilon (\R^n) = S^n.$ (One point
      compactification of $\R^n$.)
      
